### PR TITLE
added activities objects to maps and updated pngs for each map 

### PR DESCRIPTION
**Pull request by 1ucycrabtree**
add activities to each map, follows the format of previous activities: 

for example
```
[
    {
        "name": "activityStr",
        "propertytype": "",
        "type": "string",
        "value": "daydream"
    },
    {
        "name": "activityTime",
        "propertytype": "",
        "type": "int",
        "value": 1
    },
    {
        "name": "activityType",
        "propertytype": "",
        "type": "string",
        "value": "nap"
    },
    {
        "name": "changeAmount",
        "propertytype": "",
        "type": "string",
        "value": "0.15"
    },
    {
        "name": "isActivity",
        "propertytype": "",
        "type": "bool",
        "value": true
    }
]
```

### CODE REVIEW

**Comment by sammyhori** [comment]
Does this change how activities are being implemented, just add more activities or just add text boxes for each activity?

I'm not really sure what this does as I cannot find similar code in the original `.tmx` files.

**Comment by 1ucycrabtree** [comment]
> Does this change how activities are being implemented, just add more activities or just add text boxes for each activity?
> 
> I'm not really sure what this does as I cannot find similar code in the original `.tmx` files.


All three. Originally there was only one activity per building so if you walked on the '!' then it would do the activity from the map. By using the variables there can be multiple activities and activity types which helps with the implementation of score algorithm and algorithms.

**Review by sammyhori — APPROVED** [review]
Approved Changes

I'm not entirely sure what extra work will be required to implement this code but I don't think it'll cause any issues.

**Comment by LMLiam** [comment]
lgtm

**Pull request merged**
