### PR TITLE
Unit Test Updates

### PR DESCRIPTION
**Pull request by sammyhori**
## Moved character image strings

Moved the strings containing paths to the character images to the Player class and moved any changed any referrals to it to reflect the change. 

Changes:
- Added character image strings to `game/core/src/com/eng1/game/Player.java`,
- Removed character image string from `game/core/src/com/eng1/game/Play.java` and changed the references to the variables to reflect the changes,
- Removed character image strings from `game/core/src/com/eng1/game/screens/CharacterScreen.java` and replaced them with references to the constant variables,
- Changed the variable references in `game/tests/src/com/eng1/gdxtesting/AssetTests.java` to reflect the changes.

## GameStats unit tests

This tests the `game/core/src/com/eng1/game/GameStats.java` class (100% coverage).

Changes:
- Added `game/tests/src/com/eng1/gdxtesting/GameStatsUnitTests.java`.

## AppPreferences unit tests

This tests the `game/core/src/com/eng1/game/AppPreferences.java` class (100% coverage).

Changes:
- Changed the constant strings to refer to specific Gdx.app preferences `game/core/src/com/eng1/game/AppPreferences.java` to public so they could be referred to from tests,
- Added `game/tests/src/com/eng1/gdxtesting/AppPreferencesUnitTests.java`.

### CODE REVIEW

**Review by sammyhori — COMMENTED** [review]
I don't know why the build tests are failing, all the tests run fine on my local system.

image

**Comment by sammyhori** [comment]
Not sure how to resolve this, it may be worth pulling the fork (`unit-tests-2`) to your local machine and checking if you can run the tests there.

image

**Comment by LMLiam** [comment]
ignoring ci/cd

**Comment by sammyhori** [comment]
Thanks, I'm not sure what the issue was. I'll try and use individual branches (and therefore pull requests) from now on for adding unit tests to ensure that they'll work.

**Pull request merged**
