### PR TITLE
Preferences unit tests updates

### PR DESCRIPTION
**Pull request by sammyhori**
Changed:

`game/core/src/com/eng1/game/settings/Preferences.java`
Changed `NAME`s access modifier so it can accessed by unit tests.

`game/core/src/com/eng1/game/settings/MusicPreferences.java`
 Changed the constant variables' access modifiers to public so they can be accessed by unit tests.

`game/tests/src/com/eng1/gdxtesting/PreferencesUnitTests.java`
Removed tests for MusicPreferences related functions.

`game/tests/src/com/eng1/gdxtesting/MusicPreferencesUnitTests.java`
Added tests for MusicPreferences related functions and made fixes to broken references and calls.
Also added a new test for the new getKey() function.

### CODE REVIEW

**Comment by sammyhori** [comment]
It still doesn't like `testIsSoundEffectsEnabled` but doesn't complain about the others now they've been moved to a new class...

**Comment by sammyhori** [comment]
If you compare `testIsEnabled` and `testIsSoundEffectsEnabled`, there is functionally no difference and yet for some reason GitHub CI/CD doesn't like the latter one.



```
    @Test
    public void testIsEnabled() {
        assertEquals(
                "Testing whether MusicPreferences.isEnabled() works as expected.",
                Gdx.app.getPreferences(Preferences.NAME)
                        .getBoolean(
                                musicPreferences
                                        .getKey(musicPreferences.ENABLED) // getKey returns a String
                        ),                                                // which is passed into getBoolean
                musicPreferences.isEnabled() // returns a primitive boolean
        );
    }
```

```
    public void testIsSoundEffectsEnabled() {
        assertEquals(
                "Testing whether AppPreferences.isSoundEffectsEnabled() works as expected.",
                Gdx.app.getPreferences(Preferences.NAME)
                    .getBoolean(Preferences.PREF_SOUND_ENABLED), // getBoolean() is given a String
                preferences.isSoundEffectsEnabled() // returns a primitive boolean
        );
    }
```

**Comment by LMLiam** [comment]
My latest commits reversed the encapsulation breaking changes and I also changed testGetKey() to use reflection instead, which is the preferred way of doing this

**Comment by LMLiam** [comment]
For now, you should ignore sound effects, because some of my later changes moves this into a separate class.

**Comment by sammyhori** [comment]
All the pushed tests run on my local machine

image

**Comment by sammyhori** [comment]
As all tests have passed I'm going to assume this'll be merged with master and am going to branch off from this to make more unit tests

**Pull request merged**
