### PR TITLE
Removed the redundant Boolean casts in AppPreferencesUnitTests.java

### PR DESCRIPTION
**Pull request by sammyhori**
These were placed here to test if it would fix an issue with GitHub's CI/CD failing unit tests for unknown reasons

### CODE REVIEW

**Comment by sammyhori** [comment]
It still throws the same CI/CD error, I'll continue playing around in this PR to see if I can work it out.

**Comment by sammyhori** [comment]
My current train of thought is it's something to do with the fact that GitHub may run the tests in a random order whereas my IDE runs them chronologically and therefore the issues only occur when the tests are run out of order. This would make sense as to why I haven't had this issue with other unit tests as this is the first one to use an instantiated object (i.e all others were just calling static methods).

The obvious fix (if this is the issue) may be to just make all the AppPreferences methods static any ways as I can't tell why they are not (please let me know if you know why).

There may be in an issue in that the called methods are returning a `boolean` but `assertEquals()` (and I assume `assertTrue()`) expects `Booleans` so some auto-boxing is occurring and somehow an issue is occurring there, which seems to be an issue in [this StackOverflow post](https://stackoverflow.com/questions/65672776/junit-tests-fails-on-github-actions-but-not-locally) but I'm too tired (or not adept enough) to properly understand what the poster's solution and issue was so I'll reread it in the morning and see if I can make sense of it.

**Comment by LMLiam** [comment]
It runs the Gradle task, will execute the same; nonetheless unit tests should be independent and not be reliant upon one another

**Comment by LMLiam** [comment]
I've rewritten how Preferences work to align more with how we had it in the last project, so this is something you will need to rewrite. My refactoring already changed the references, but the actual logic of the unit tests may need to change

**Comment by LMLiam** [comment]
I'm speeding through what I can here in terms of coding, I switched back to master and have been dropping updates in as my other commit history got completely fucked, wouldn't even reset back to HEAD, so I've just been copying things over and also making it better as I go

**Comment by sammyhori** [comment]
> I've rewritten how Preferences work to align more with how we had it in the last project, so this is something you will need to rewrite. My refactoring already changed the references, but the actual logic of the unit tests may need to change

Cool, I'll make a new branch and sort the tests again, it'll be easier than trying to resort it on this branch.

**Pull request closed without merging**
